version: '3.9'

services:
  wordpress:
    container_name: ${PROJECT_ID}_wordpress
    image: wordpress:5.9
    volumes:
      - ./src/.htaccess:/var/www/html/.htaccess
      - ./src/wp-content/themes:/var/www/html/wp-content/themes
      - ./src/wp-content/plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
    ports:
      - ${PORT}:80
    networks:
      - webnet
    restart: always

  db:
    container_name: ${PROJECT_ID}_db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge

volumes:
  db_data:
